# Default configuration for quantum drug discovery experiments

# Data configuration
data:
  path: "data/processed/molecules.csv"
  mol_column: "smiles"
  representation: "smiles"  # smiles or selfies
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  max_molecules: null  # null for all molecules
  min_length: 3
  max_length: 100

# Model configuration
model:
  type: "hybrid"  # qcbm, hybrid, lstm
  
  # Quantum circuit parameters
  quantum:
    n_qubits: 10
    n_layers: 4
    device: "default.qubit"  # PennyLane device
    entangling_pattern: "linear"  # linear, circular, all-to-all
    rotation_gates: ["RX", "RZ"]
    shots: null  # null for exact simulation
    
  # Classical model parameters  
  classical:
    seq_len: 100
    vocab_size: null  # auto-detected if null
    embedding_dim: 64
    hidden_dim: 128
    lstm_layers: 2
    dropout: 0.1
    projection_dim: 64
    
  # Special tokens
  tokens:
    padding_idx: 0
    sos_token: 1
    eos_token: 2

# Training configuration
training:
  batch_size: 32
  n_epochs: 100
  learning_rate: 1e-3
  quantum_learning_rate: 1e-2
  lambda_quantum: 0.1  # weight for quantum loss in hybrid training
  
  # Optimization
  optimizer: "adam"
  weight_decay: 1e-5
  grad_clip_norm: 1.0
  
  # Scheduling
  scheduler: null  # cosine, exponential, step, null
  scheduler_params:
    gamma: 0.95  # for exponential/step
    step_size: 20  # for step
  
  # Regularization
  dropout: 0.1
  label_smoothing: 0.0

# Evaluation configuration
evaluation:
  eval_interval: 10  # epochs
  n_samples: 1000
  temperature: 1.0
  
  # Metrics
  compute_validity: true
  compute_uniqueness: true
  compute_novelty: true
  compute_drug_likeness: true
  compute_diversity: true
  
  # Filtering
  filters:
    use_lipinski: true
    use_pains: true
    use_structural: true
    lipinski_violations_max: 2

# Logging and checkpoints
logging:
  log_interval: 100
  save_dir: "./experiments"
  experiment_name: null  # auto-generated if null
  log_level: "INFO"
  save_checkpoints: true
  checkpoint_interval: 20  # epochs
  keep_best_only: false
  
  # Wandb integration (optional)
  use_wandb: false
  wandb_project: "quantum-drug-discovery"
  wandb_entity: null

# Hardware configuration
hardware:
  device: "auto"  # cpu, cuda, mps, auto
  num_workers: 4
  pin_memory: true
  mixed_precision: false

# Reproducibility
seed: 42
deterministic: false
