title: "Soma - Personalized Medicine Research"
description: "Advancing personalized medicine through cutting-edge computational methods"
url: "https://shawngibford.github.io"
baseurl: "/soma"

# Social links
github_username: soma-quantum
linkedin_username: soma-quantum
twitter_username: SomaQuantum

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom settings for GitHub Pages
permalink: pretty
sass:
  style: compressed
